### register
POST http://127.0.0.1:8000/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "email": "test1@mail.com",
    "password": "12345678"

}

### login
POST http://127.0.0.1:8000/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "12345678"
}

### get user
GET http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|dh6h64aYaBAFEXkoPfhKBKvCK6Ub2KSM6EmBncMG

### logout
POST http://127.0.0.1:8000/api/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|dh6h64aYaBAFEXkoPfhKBKvCK6Ub2KSM6EmBncMG

### update user
PUT http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|dh6h64aYaBAFEXkoPfhKBKvCK6Ub2KSM6EmBncMG

{
    "name": "testing ke satu",
    "email": "admin@mail.com"
}