### register
POST http://127.0.0.1:8000/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "email": "test1@mail.com",
    "password": "12345678"

}

### login
POST http://127.0.0.1:8000/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "test1@mail.com",
    "password": "123456789"
}

### get user
GET http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|TayR20zRKCFTY0JYXATMuPd9TDuhShBG95LBBl4r

### logout
POST http://127.0.0.1:8000/api/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|TayR20zRKCFTY0JYXATMuPd9TDuhShBG95LBBl4r
### update user
PUT http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|TayR20zRKCFTY0JYXATMuPd9TDuhShBG95LBBl4r

{
    "name": "testing ke satu",
    "email": "test1@mail.com",
    "password": "123456789"
}