
### contact
POST http://127.0.0.1:8000/api/contact
Accept: application/json
Content-Type: application/json

{
    "name": "testing",
    "email": "fajasuhanaaa@gmail.com",
    "subject": "testing",
    "keterangan": "saya ingin donasi nih"
}

### get all contact
GET http://127.0.0.1:8000/api/contact
Accept: application/json
Content-Type: application/json
