
### contact
POST http://127.0.0.1:8000/api/contact
Accept: application/json
Content-Type: application/json

{
    "name": "Rifqi",
    "email": "rifqi1136@gmail.com",
    "subject": "naonwe",
    "keterangan": "saya ingin donasi nih"
}

### get all contact
GET http://127.0.0.1:8000/api/contact
Accept: application/json
Content-Type: application/json

### get contact by id
GET http://127.0.0.1:8000/api/contact/1
Accept: application/json
Content-Type: application/json

### delete contact by id
DELETE http://127.0.0.1:8000/api/contact/1
Accept: application/json
Content-Type: application/json

### delete all contact
DELETE http://127.0.0.1:8000/api/contact
Accept: application/json
Content-Type: application/json
