### create donate
POST http://127.0.0.1:8000/api/donate
Accept: application/json
Content-Type: application/json

{
    "jenis_donasi": "zakat",
    "nominal": 100000,
    "nama": "test",
    "alamat": "test",
    "rekening_id": 1,
    "telepon": "081234567890",
    "email": "mirasopie1@gmail.com",
    "keterangan": "test",
    "bukti_pembayaran": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}

### approve donate
PUT http://127.0.0.1:8000/api/donate/4
Accept: application/json
Content-Type: application/json
Authorization:Bearer 3|1EVXFOsKvfwYW3sVnAOLdyxstVlOQ5XQjEgxfTHC
    
    {
    "status": "reject"
    }