### Add Data Rekening
POST http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xraVj4Fr6X2Hmh070PR5NQwmR4IJvtkD0nGKZKAp

{
    "nomor_rekening" : "2736842",
    "nama_bank" : "BANK MANDIRI",
    "atas_nama" : "Dedi Supardi"
}


### Get All Data Rekening
GET http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json

### get Data Rekening
GET  http://127.0.0.1:8000/api/rekening/4
Accept: application/json
Content-Type: application/json

