### Add Data Rekening
POST http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|JWHBwM0Da5wh15tao0tNYSQ5YmHjpzZA1EPqprVC

{
    "nomor_rekening" : "273687722222",
    "nama_bank" : "BANK MANDIRI",
    "atas_nama" : "Dedi Supardi"
}


### Get All Data Rekening
GET http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json

### get Data Rekening
GET  http://127.0.0.1:8000/api/rekening/1
Accept: application/json
Content-Type: application/json

### Update Data Rekening
PUT http://127.0.0.1:8000/api/rekening/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|JWHBwM0Da5wh15tao0tNYSQ5YmHjpzZA1EPqprVC

{
    "nomor_rekening" : "555555555",
    "nama_bank" : "BANK MANDIRI",
    "atas_nama" : "Dedi Supardi"
}

### Delete Data Rekening 
DELETE http://127.0.0.1:8000/api/rekening/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 4|uvQzblA3Qs2m8K2MW6Q7zbdzsl2E7c0ktDzJrom7

### Delete all Data Rekening
DELETE http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json
Authorization: Bearer 4|uvQzblA3Qs2m8K2MW6Q7zbdzsl2E7c0ktDzJrom7

### Get Data Rekening
GET http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json

### Get Data Rekening by ID
GET http://127.0.0.1:8000/api/rekening/12
Accept: application/json
Content-Type: application/json