### Add Data Rekening
POST http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|HjjBPERwBrdNGhSWmkCqhewQuaITGSCSLojsm4dK

{
    "nomor_rekening" : "1234567890",
    "nama_bank" : "BANK CENTRAL ASIA",
    "atas_nama" : "Dedi Supardi"
}


### Get All Data Rekening
GET http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json

### get Data Rekening
GET  http://127.0.0.1:8000/api/rekening/3
Accept: application/json
Content-Type: application/json

### Update Data Rekening
PUT http://127.0.0.1:8000/api/rekening/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|HjjBPERwBrdNGhSWmkCqhewQuaITGSCSLojsm4dK

{
    "nomor_rekening" : "12345678910",
    "nama_bank" : "BANK CENTRAL ASIA",
    "atas_nama" : "Dedi Supardi"
}

### Delete Data Rekening
DELETE http://127.0.0.1:8000/api/rekening/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|HjjBPERwBrdNGhSWmkCqhewQuaITGSCSLojsm4dK

### Delete All Data Rekening
DELETE http://127.0.0.1:8000/api/rekening
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|HjjBPERwBrdNGhSWmkCqhewQuaITGSCSLojsm4dK

